#MINI CALCULADORA
print('MINI CALCULADORA DE INTEIROS')
N1 = int(input('FORNEÇA O VALOR DE N1'))
N2 = int(input('FORNEÇA O VALOR DE N2'))
print('AQUI ESTÃO AS OPERAÇÕES BASICAS:')
print(f'ADIÇÃO                 : {N1} + {N2} = {N1 + N2}')
print(f'SUBTRAÇÃO              : {N1} - {N2} = {N1 - N2}')
print(f'MULTIPLICAÇÃO          : {N1} * {N2} = {N1 * N2}')
print(f'DIVISÃO                : {N1} / {N2} = {N1 / N2}')
print(f'DIV (Quociente Inteiro): {N1} // {N2} = {N1 // N2}')
print(f'MOD (Resto da Divisão) : {N1} % {N2} = {N1 % N2}')
print(f'POTÊNCIAÇÃO            : {N1} ** {N2} = {N1 ** N2} ')
print(f'RADICIAÇÃO     : N1 ** (N2 / 2) = {N1} ** {1/N2} = {N1 ** (1/N2): .1f}')